pull_request_rules:
  - name: Automatic merge if not paths-ignore
    conditions:
      - -files~=^docs/
      - -files~=^.md
      - -files~=^scripts/cleanup/
      - base=main
      - base=release-*
      - "check-success=Shellcheck"
      - "check-success=Lint"
      - "check-success=Tidy"
      - "check-success=Mocks"
      - "check-success=Chart checks"
      - "check-success=Go build"
      - "#approved-reviews-by>=2"
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge if paths-ignore
    conditions:
      - files~=^docs/
      - files~=^.md
      - files~=^scripts/cleanup/
      - base=main
      - base=release-*
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic rebase
    conditions:
      - -conflict
      - -draft
    actions:
      rebase: {}
