pull_request_rules:
  - name: Automatic merge on main
    conditions:
      - -files~=^docs/
      - base=main
      - "check-success=Shellcheck"
      - "check-success=Lint"
      - "check-success=Tidy"
      - "check-success=Mocks"
      - "check-success=Chart checks"
      - "check-success=Go build"
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic rebase
    conditions:
      - -conflict
      - -draft
    actions:
      update: {}
