pull_request_rules:
  - name: Automatic merge if not paths-ignore
    conditions:
      - base=main
      - "check-success=Shellcheck"
      - "check-success=Lint"
      - "check-success=Tidy"
      - "check-success=Mocks"
      - "check-success=Chart checks"
      - "check-success=Go build"
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge if docs
    conditions:
      - files~=^docs/
      - -files!=^docs/
      - base=main
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge if markdown
    conditions:
      - files~=^.md
      - -files!=^.md
      - base=main
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge if scripts/cleanup
    conditions:
      - files~=^scripts/cleanup/
      - -files!=^scripts/cleanup/
      - base=main
      - label=automerge
      - -label=wip
      - -label=do-not-merge/hold
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic rebase
    conditions:
      - -conflict
      - -draft
    actions:
      rebase: {}
