name: automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      if: ${{ github.event.label.name == 'automerge' }}
      uses: actions/checkout@v1
    - name: Check status
      if: ${{ github.event.label.name == 'automerge' }}
      run: bash scripts/status-checker.sh ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}
    - name: automerge
      if: ${{ github.event.label.name == 'automerge' }}
      uses: "pascalgn/automerge-action@v0.13.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_METHOD: "merge"
        MERGE_LABELS: "automerge,!wip,!do-not-merge/hold"
        MERGE_RETRIES: "0"
        UPDATE_METHOD: "rebase"
