name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate token
      id: generate_token
      run: |
        issueTime=$(date +%s)
        expireTime=$(date -d "$EXPIRE_TIME + 600 seconds" +%s)
        header=$(echo '{ "alg": "RS256", "typ": "JWT" }' | jq -r '(. | @base64)')
        payload=$(echo '{"iss":"${secrets.APP_ID}","iat": '$ISSUE_TIME' ,"exp":'$EXPIRE_TIME'}'| jq -r '(. | @base64)'| sed s/\+/-/ | sed -E s/=+$//)
        echo $payload
        signature=$(echo -n "$header.$payload" | openssl dgst -sha256 -binary -sign ${secrets.APP_PRIVATE_KEY} | openssl enc -base64 | tr -d '\n=' | tr -- '+/' '-_')
        echo $signature
        tokenURL=$(curl -i -X GET -H "Authorization: Bearer $header.$payload.$signature" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations | grep 'access_tokens_url' | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//')
        echo $tokenURL
        token=$(curl -i -X POST -H "Authorization: Bearer $header.$payload.$signature" -H "Accept: application/vnd.github.v3+json" $tokenURL | grep 'token'|awk '{print $2}'| sed -e 's/^"//' -e 's/",$//')"
        echo "::set-output name=token::$token
    - name: automerge
      uses: "pascalgn/automerge-action@v0.13.0"
    env:
      GITHUB_TOKEN: $token
      MERGE_METHOD: "merge"
      MERGE_LABELS: "automerge,!wip,!do-not-merge/hold"
      UPDATE_METHOD: "rebase"
