name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - reopened
jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && !contains(github.event.pull_request.labels.*.name, 'wip') && !contains(github.event.pull_request.labels.*.name, 'do-not-merge/hold')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check status
      run: bash scripts/status-checker.sh ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}
    - name: automerge
      uses: "pascalgn/automerge-action@v0.13.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_METHOD: "merge"
        MERGE_LABELS: "automerge,!wip,!do-not-merge/hold"
        MERGE_RETRIES: "0"
        UPDATE_METHOD: "rebase"
    - name: Check if merged
      run: |
        echo ${github.number}
        bash scripts/check-merge-state.sh ${github.number}
