name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate token
      id: generate_token
      env:
        ID: ${{secrets.APP_ID}}
        PK: ${{secrets.APP_PRIVATE_KEY}}
      run: |
        source scripts/generate_token.sh $ID $PK
        echo "GITHUB_TOKEN=$token" >> "$GITHUB_ENV"
    - name: automerge
      uses: "pascalgn/automerge-action@v0.13.0"
      env:
        MERGE_METHOD: "merge"
        MERGE_LABELS: "automerge,!wip,!do-not-merge/hold"
        MERGE_RETRY_SLEEP: "300000"
        UPDATE_LABELS: "automerge"
        UPDATE_METHOD: "rebase"
