name: Validate automerge
on:
  workflow_run:
    workflows:
      - "Automerge"
    types: completed
jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && !contains(github.event.pull_request.labels.*.name, 'wip') && !contains(github.event.pull_request.labels.*.name, 'do-not-merge/hold')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check if successful automerge
      run: bash scripts/check-automerge-status.sh ${GITHUB_REPOSITORY} ${{ github.event.number }} || exit 1
    - name: Re-trigger status checks if rebased
      if: ${{ failure() }}
      run: bash scripts/check-if-rebased.sh ${GITHUB_REPOSITORY} ${{ github.event.number }} ${{ secrets.GITHUB_TOKEN }}
